# db_path: ":memory:"
db_path: ./.private/db.sqlite3
controlnet_references_path: ./.private/generated_images
ipadapter_references_path: ./.private/poses_images
thumbnails_path: ./.private/huggingface
