# db_path: ":memory:"
db_path: ./.private/db.sqlite3
controlnet_references_path: ./.private/controlnet_images
ipadapter_references_path: ./.private/ipadapter_images
thumbnails_path: ./.private/thumbnail_images
